name: Node Continuous Integration
on: 
  pull_request:

  jobs: 
    test_pull_request:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@2
        - uses: actions/setup-node@v1
          with:
            node-version: 18
        - run: npm ci
        - run: npm run test:unit